# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_test',
                'doc_host': 'https://redam94.github.io',
                'git_url': 'https://github.com/redam94/nbdev_test',
                'lib_path': 'nbdev_test'},
  'syms': {'nbdev_test.core': {'nbdev_test.core.say_hello': ('core.html#say_hello', 'nbdev_test/core.py')}}}